# Generated by Django 3.2.8 on 2021-12-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0010_remove_account_telegram_chat_id"),
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notifier", old_name="notifier", new_name="type"
        ),
        migrations.AlterUniqueTogether(
            name="notifier", unique_together={("account", "type")}
        ),
    ]
