# Generated by Django 3.2.8 on 2021-12-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_account_account_contacts_data"),
        (
            "notification",
            "0001_squashed_0003_alter_notifier_telegram_chat_id_squashed_0002_auto_20211227_1015",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_event",
                    models.CharField(
                        choices=[
                            ("SUCCESS_OFFER", "SUCCESS_OFFER"),
                            ("SALESDASHBOARD_SOON_OVER", "SALESDASHBOARD_SOON_OVER"),
                            ("SALESDASHBOARD_IS_OVER", "SALESDASHBOARD_IS_OVER"),
                        ],
                        max_length=50,
                    ),
                ),
                ("enable", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TELEGRAM", "TELEGRAM"),
                            ("EMAIL", "EMAIL"),
                            ("VK", "VK"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
        ),
    ]
