# Generated by Django 3.2.8 on 2022-01-04 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_account_account_contacts_data"),
        ("notification", "0002_consumer_notificationsubscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consumers",
                to="account.account",
            ),
        ),
        migrations.AlterField(
            model_name="notificationsubscription",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_subscriptions",
                to="account.account",
            ),
        ),
    ]
