# Generated by Django 3.2.8 on 2022-01-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_auto_20220106_0812"),
        ("notification", "0003_auto_20220104_0825"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="notifier", unique_together=None),
        migrations.RemoveField(model_name="notifier", name="account"),
        migrations.RemoveField(model_name="notifier", name="type"),
        migrations.AlterUniqueTogether(
            name="consumer", unique_together={("account", "type")}
        ),
        migrations.AlterUniqueTogether(
            name="notificationsubscription",
            unique_together={("account", "notification_type")},
        ),
        migrations.DeleteModel(name="NotificationType"),
        migrations.DeleteModel(name="Notifier"),
    ]
