# Generated by Django 3.2.11 on 2022-01-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notification", "0004_auto_20220106_0825")]

    operations = [
        migrations.AddField(
            model_name="notificationsubscription",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        )
    ]
