# Generated by Django 3.2.11 on 2022-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notification", "0005_notificationsubscription_data")]

    operations = [
        migrations.AlterField(
            model_name="notificationsubscription",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("SUCCESS_OFFER", "SUCCESS_OFFER"),
                    ("SALESDASHBOARD_SOON_OVER", "SALESDASHBOARD_SOON_OVER"),
                    ("SALESDASHBOARD_IS_OVER", "SALESDASHBOARD_IS_OVER"),
                    ("NEW_SALESDASHBOARD", "NEW_SALESDASHBOARD"),
                    ("ASSET_PRICE_HAS_BEEN_DROPPED", "ASSET_PRICE_HAS_BEEN_DROPPED"),
                ],
                max_length=50,
            ),
        )
    ]
