# Generated by Django 3.2.11 on 2022-02-04 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_alter_account_account_token"),
        ("notification", "0005_notificationsubscription_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerNotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable", models.BooleanField(default=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SUCCESS_OFFER", "SUCCESS_OFFER"),
                            ("SALESDASHBOARD_SOON_OVER", "SALESDASHBOARD_SOON_OVER"),
                            ("SALESDASHBOARD_IS_OVER", "SALESDASHBOARD_IS_OVER"),
                            ("NEW_SALESDASHBOARD", "NEW_SALESDASHBOARD"),
                            (
                                "ASSET_PRICE_HAS_BEEN_DROPPED",
                                "ASSET_PRICE_HAS_BEEN_DROPPED",
                            ),
                            ("ASSET_APPEARED_ON_MARKET", "ASSET_APPEARED_ON_MARKET"),
                            (
                                "ASSET_PRICE_HAS_BEEN_DROPPED_ON_MARKET",
                                "ASSET_PRICE_HAS_BEEN_DROPPED_ON_MARKET",
                            ),
                            (
                                "ASSET_PRICE_HAS_BEEN_RICED_ON_MARKET",
                                "ASSET_PRICE_HAS_BEEN_RICED_ON_MARKET",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to="account.broker",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("account", "notification_type")},
            },
        ),
        migrations.CreateModel(
            name="ClientNotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable", models.BooleanField(default=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("NEW_SALESDASHBOARD", "NEW_SALESDASHBOARD"),
                            (
                                "ASSET_PRICE_HAS_BEEN_DROPPED",
                                "ASSET_PRICE_HAS_BEEN_DROPPED",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to="account.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("account", "notification_type")},
            },
        ),
        migrations.DeleteModel(name="NotificationSubscription"),
    ]
