apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower
  namespace: dev
  labels:
    deployment: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: celery-flower
  template:
    metadata:
      labels:
        pod: celery-flower
    spec:
      containers:
      - name: flower
        image: ${BE_IMAGE_NAME}
        command: ['celery', '-A', 'cryptostock', 'flower']
        ports:
          - containerPort: 5555
        envFrom:
          - configMapRef:
              name: cryptostock-dev-config
        resources:
          limits:
            cpu: 100m
