version: '3'
services:
  database:
    image: "postgres"  # use the latest official postgres version
    env_file:
      - dev.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - $POSTGRES_PORT:5432
  redis:
    image: "redis"  # use the latest official redis version
    ports:
      - $REDIS_PORT:6379

volumes:
  database-data: # named volumes can be managed easier using docker-compose
