# Generated by Django 3.2.8 on 2021-12-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("asset", "0002_alter_asset_description")]

    operations = [
        migrations.AlterUniqueTogether(
            name="asset", unique_together={("name", "description")}
        )
    ]
