apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot
  namespace: dev
  labels:
    app: telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
        - name: telegram-bot
          image: ${NOTIFICATION_BOTS_IMAGE_NAME}
          command: ['python3', '-m', 'telegram_bot']

          envFrom:
            - configMapRef:
                name: cryptostock-dev-config
