# Generated by Django 3.2.8 on 2021-12-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("asset", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        )
    ]
