# Generated by Django 3.2.8 on 2021-10-21 08:22

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("asset", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "count",
                    utils.fields.CountField(
                        decimal_places=4,
                        default=0,
                        max_digits=25,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="asset.asset",
                    ),
                ),
            ],
        )
    ]
