# Generated by Django 3.2.8 on 2021-10-21 15:21

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import utils.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wallet", "0001_initial"), ("asset", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="wallet", name="asset"),
        migrations.RemoveField(model_name="wallet", name="count"),
        migrations.CreateModel(
            name="WalletRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    utils.modules.CountField(
                        decimal_places=4,
                        default=0,
                        max_digits=25,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_record",
                        to="asset.asset",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_record",
                        to="wallet.wallet",
                    ),
                ),
            ],
        ),
    ]
