# Generated by Django 3.2.8 on 2021-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("asset", "0001_initial"), ("wallet", "0002_auto_20211013_1128")]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="assets",
            field=models.ManyToManyField(
                related_name="wallet",
                through="wallet.WalletAssistant",
                to="asset.Asset",
            ),
        )
    ]
