version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db_store:/var/lib/postgresql/data
    env_file:
      - docker.dev.env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  be_build:
    build: ../cryptostock_api/cryptostock/
    env_file:
      - docker.dev.env
    command: >
        bash -c "python3 manage.py makemigrations &&
        python3 manage.py migrate &&
        python3 manage.py collectstatic --noinput"
    depends_on:
      - db
    volumes:
      - static_volume:/home/code/staticfiles

  gunicorn:
    build: ../cryptostock_api/cryptostock/
    env_file:
      - docker.dev.env
    command: gunicorn -b 0.0.0.0:8000 cryptostock.wsgi:application
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
      - be_build
    volumes:
      - static_volume:/home/code/staticfiles

  celery:
    build: ../cryptostock_api/cryptostock/
    env_file:
      - docker.dev.env
    restart: always
    command: celery -A cryptostock worker -l info
    depends_on:
      - redis
      - be_build

volumes:
  db_store:
  static_volume:
