version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db_store:/var/lib/postgresql/data
    env_file:
      - docker.dev.env
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  be:
    build: ../cryptostock_api/cryptostock/
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - docker.dev.env
    depends_on:
      - db

  celery:
    build: ../cryptostock_api/cryptostock/
    restart: always
    command: celery -A cryptostock worker -l info
    env_file:
      - docker.dev.env
    links:
      - redis:redis
    depends_on:
      - redis
      - be

volumes:
  db_store:
