# Generated by Django 3.2.8 on 2021-10-21 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="offer", name="asset"),
        migrations.RemoveField(model_name="offer", name="broker"),
        migrations.RemoveField(model_name="offer", name="price"),
        migrations.AddField(
            model_name="offer",
            name="deal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer",
                to="account.salesdashboard",
            ),
            preserve_default=False,
        ),
    ]
