# Generated by Django 3.2.8 on 2021-11-22 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0003_auto_20211116_1608")]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="account.client"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="offer",
                to="account.salesdashboard",
            ),
        ),
    ]
