# Generated by Django 3.2.8 on 2021-12-17 15:13

from decimal import Decimal

import django.core.validators
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0007_purchasedashboard_timestamp")]

    operations = [
        migrations.AddField(
            model_name="salesdashboard",
            name="count_control_notification",
            field=utils.fields.CountField(
                blank=True,
                decimal_places=4,
                default=0,
                help_text="input here min count, after which you want get notification (if you want).",
                max_digits=14,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
            ),
        ),
        migrations.AddField(
            model_name="salesdashboard",
            name="success_offer_notification",
            field=models.BooleanField(
                default=False,
                help_text="turned on notification after every success offer. On default - off.",
            ),
        ),
    ]
