# Generated by Django 3.2.8 on 2021-12-27 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0009_auto_20211221_1555")]

    operations = [
        migrations.RemoveField(model_name="account", name="telegram_chat_id"),
        migrations.AlterField(
            model_name="salesdashboard",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.broker",
            ),
        ),
    ]
