# Generated by Django 3.2.8 on 2021-12-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0009_auto_20211221_1555")]

    operations = [migrations.RemoveField(model_name="account", name="telegram_chat_id")]
