# Generated by Django 3.2.8 on 2021-12-24 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0010_remove_account_telegram_chat_id")]

    operations = [
        migrations.AlterField(
            model_name="salesdashboard",
            name="broker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.broker",
            ),
        )
    ]
