# Generated by Django 3.2.8 on 2022-01-06 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_alter_asset_description"),
        ("market", "0002_auto_20211206_1257"),
        ("account", "0011_account_account_contacts_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="account_contacts_data"),
        migrations.AlterField(
            model_name="offer",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="account.client",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="deal",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offer",
                to="account.salesdashboard",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedashboard",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asset.asset"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedashboard",
            name="market",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="market.market",
            ),
        ),
        migrations.AlterField(
            model_name="salesdashboard",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="asset.asset"
            ),
        ),
    ]
