# Generated by Django 3.2.11 on 2022-01-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("account", "0013_auto_20220106_1353")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_token",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        )
    ]
