# Generated by Django 3.2.8 on 2021-10-18 17:47

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import utils.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_auto_20211013_1128"),
        ("asset", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="wallet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account",
                to="wallet.wallet",
            ),
        ),
        migrations.CreateModel(
            name="AssetBuy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy_count",
                    utils.modules.CountField(
                        decimal_places=4,
                        default=0,
                        max_digits=25,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="asset.asset"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="account.client"
                    ),
                ),
            ],
        ),
    ]
