# Generated by Django 3.2.8 on 2021-12-09 16:00

from decimal import Decimal

import django.core.validators
import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0005_purchasedashboard")]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="cash_balance",
            field=utils.fields.CountField(
                decimal_places=2,
                default=0,
                max_digits=30,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
            ),
        )
    ]
