# Generated by Django 3.2.8 on 2021-12-09 16:06

from decimal import Decimal

import django.core.validators
import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0006_alter_account_cash_balance")]

    operations = [
        migrations.AlterField(
            model_name="purchasedashboard",
            name="price",
            field=utils.fields.PriceField(
                decimal_places=2,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="salesdashboard",
            name="price",
            field=utils.fields.PriceField(
                decimal_places=2,
                max_digits=16,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
