# Generated by Django 3.2.8 on 2021-12-09 16:11

from decimal import Decimal

import django.core.validators
import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("account", "0007_auto_20211209_1606")]

    operations = [
        migrations.AlterField(
            model_name="purchasedashboard",
            name="count",
            field=utils.fields.CountField(
                decimal_places=0,
                default=0,
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
            ),
        )
    ]
