kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres-pv
